version: "3.5"
services:
  spark-master:
    image: spark-cluster/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./src:/opt/src
      - ./data:/opt/data
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "SPARK_MASTER_LOG=/opt/spark/logs/"
    command: ["/opt/start-master.sh"]
  spark-worker:
    image: spark-cluster/spark:latest
    depends_on:
      - spark-master
    volumes:
      - ./src:/opt/src
      - ./data:/opt/data
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_WORKER_LOG=/opt/spark/logs/"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=1G"
      - "SPARK_EXECUTOR_MEMORY=1G"
    command: ["/opt/start-worker.sh"]
networks:
  spark-network:
    name: "spark-cluster-network"
    driver: bridge
    ipam:
      driver: default
