# These are the default values for the Helm Spark chart
# https://github.com/helm/charts/tree/master/stable/spark

# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Master:
  Name: master
  Image: "kwendel/qpe"
  ImageTag: "latest"
  Replicas: 1
  Component: "spark-master"
  Fullname: "test-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  # DaemonMemory: 1g
  ServiceType: LoadBalancer

WebUi:
  Name: webui
  Fullname: "test-webui"
  ServicePort: 8080
  ContainerPort: 8080
