# These are the default values for the Helm Spark chart
# https://github.com/helm/charts/tree/master/stable/spark

# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Master:
  Fullname: "test-master"
  ServicePort: 7077

WebUi:
  Name: webui
  Fullname: "test-webui"
  ServicePort: 8080
  ContainerPort: 8080

Submit:
  name: submit
  Image: "kwendel/qpe"
  ImageTag: "latest"
  Component: "spark-submit"
  Fullname: "test-submit"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 8081
  ContainerPort: 8081
