# These are the default values for the Helm Spark chart
# https://github.com/helm/charts/tree/master/stable/spark

# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Master:
  Fullname: "test-master"
  Namespace: "spark"
  ServicePort: 7077

WebUi:
  Name: webui
  Fullname: "test-webui"
  ServicePort: 8080
  ContainerPort: 8080

Worker:
  Name: worker
  Image: "kwendel/qpe"
  ImageTag: "latest"
  Replicas: 1
  Component: "spark-worker"
  Fullname: "test-worker"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 8081
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  # DaemonMemory: 1g
  # Set how much total memory workers have to give executors
  # ExecutorMemory: 1g
  Autoscaling:
    Enabled: false
  ReplicasMax: 10
  CpuTargetPercentage: 50
